# Generated by Django 5.0.6 on 2024-07-08 11:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rag_sample_app', '0003_rename_created_at_chathistory_timestamp_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='chathistory',
            name='thread_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chats', to='rag_sample_app.thread'),
        ),
    ]
