# Generated by Django 5.0.6 on 2024-07-13 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rag_sample_app", "0004_thread_alter_chathistory_thread_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="thread",
            name="summary",
            field=models.TextField(blank=True, null=True),
        ),
    ]
